# 1. Importing the MODULE

In [ ]:
import pandas as pd

# 2. Opening a local csv **file**

In [ ]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")
#printing the content
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

# 3. Open a csv file form url

In [ ]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)
df = pd.read_csv(data)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# 4. Sep Parameter for tsv files

In [ ]:
# here you can use any tsv files
df = pd.read_csv('name-of-tsv-file.tsv',sep='\t')

# 5. Index_col parameter

In [ ]:
pd.read_csv('placement.csv',index_col='Unnamed: 0')
# Here we have index column already so we maked that column as our index column

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

# 6. Header Parameter

In [ ]:
pd.read_csv('placement.csv',header=1)
# making same header of for dataframe as the csv file does

     0  6.8  123.0  1
0    1  5.9  106.0  0
1    2  5.3  121.0  0
2    3  7.4  132.0  1
3    4  5.8  142.0  0
4    5  7.1   48.0  1
..  ..  ...    ... ..
94  95  4.3  200.0  0
95  96  4.4   42.0  0
96  97  6.7  182.0  1
97  98  6.3  103.0  1
98  99  6.2  113.0  1

[99 rows x 4 columns]

# 7. use_cols parameter

In [ ]:
pd.read_csv('placement.csv',usecols=['cgpa','iq','placement'])

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

# 8. Squeeze parameters

In [ ]:
df1 = pd.read_csv("placement.csv",usecols=['cgpa'])
df1 = df1.squeeze(axis=1)
df1
# Here we are converting  pandas dataframe into pandas series

0     6.8
1     5.9
2     5.3
3     7.4
4     5.8
     ...
95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, Length: 100, dtype: float64

# 9. skiprows/nrows parameter

In [ ]:
pd.read_csv("placement.csv",index_col='Unnamed: 0',skiprows=[2,3])
# here we can see row 1 and 2 is getting skipped

    cgpa     iq  placement
0    6.8  123.0          1
3    7.4  132.0          1
4    5.8  142.0          0
5    7.1   48.0          1
6    5.7  143.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[98 rows x 3 columns]

In [ ]:
pd.read_csv("placement.csv",index_col='Unnamed: 0',nrows=50)
# It is going to take 50 rows.
# When there is big data then it is useful method of taking only some specific rows

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
5    7.1   48.0          1
6    5.7  143.0          0
7    5.0   63.0          0
8    6.1  156.0          0
9    5.1   66.0          0
10   6.0   45.0          1
11   6.9  138.0          1
12   5.4  139.0          0
13   6.4  116.0          1
14   6.1  103.0          0
15   5.1  176.0          0
16   5.2  224.0          0
17   3.3  183.0          0
18   4.0  100.0          0
19   5.2  132.0          0
20   6.6  120.0          1
21   7.1  151.0          1
22   4.9  120.0          0
23   4.7   87.0          0
24   4.7  121.0          0
25   5.0   91.0          0
26   7.0  199.0          1
27   6.0  124.0          1
28   5.2   90.0          0
29   7.0  112.0          1
30   7.6  128.0          1
31   3.9  109.0          0
32   7.0  139.0          1
33   6.0  149.0          0
34   4.8  163.0          0
35   6.8   90.0          1
36   5.7  140.0          0
37   8.1  149.0          1
38   6.5  160.0          1
39   4.6  146.0          0
40   4.9  134.0          0
41   5.4  114.0          0
42   7.6   89.0          1
43   6.8  141.0          1
44   7.5   61.0          1
45   6.0   66.0          1
46   5.3  114.0          0
47   5.2  161.0          0
48   6.6  138.0          1
49   5.4  135.0          0

# 10. Encoding parameters

In [ ]:
''' sometimes you will get the file which not opening by simple command pd.read_csv()
    and getting error like UNICODE/DECODE ERROR then you need to specifically metion
    the name of encoding to open that file.
'''
pd.read_csv('zomato.csv',encoding='latin-1')

# 11. skip bad lines

In [ ]:
pd.read_csv("your_csv_file_name",sep='anything  ; \t , - ',error_bad_lines=False)
# if you get the error like ERROR TOKENIZING DATA then use
# error_bad_lines = Flase
# It will ignore those lines and make your code perfect for model building

# 12. Handling Datetime format

In [ ]:
"""  some times your csv file may contain the "date" column which is in the form
 of string to make that column in datetime format we use folliowing command
"""
df1 = pd.read_csv("matches.csv")
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [ ]:
# now you can see that your values are getting converted into datetime64[ns]
df1 = pd.read_csv("matches.csv", parse_dates=['date'])

df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   datetime64[ns]
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(1), object(15)
memory usage: 171.2+ KB

# 14. Converters

In [ ]:
pd.read_csv("matches.csv")
'''  Here we are converting long-form of team names into its short forms using converters '''

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [ ]:
def rename(name):
  if name == 'Royal Challengers Bangalore':
    return 'RCB'
  elif name == 'Mumbai Indians':
    return 'MI'
  elif name == 'Kolkata Knight Riders':
    return 'KKR'
  elif name == 'Kings XI Punjab':
    return 'KXIP'
  elif name == 'Chennai Super Kings':
    return 'CSK'
  elif name == 'Rajasthan Royals':
    return 'RR'
  elif name == 'Delhi Daredevils':
    return 'DD'
  elif name == 'Deccan Chargers':
    return 'DC'
  elif name == 'Sunrisers Hyderabad':
    return 'SRH'
  else:
    return name

In [ ]:
rename('Royal Challengers Bangalore')

'RCB'

In [ ]:
# applying the converter/function  to dataframe to change the names
pd.read_csv("matches.csv",converters={"team1":rename})

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",KXIP,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,DD,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,MI,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,KKR,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",SRH,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",SRH,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",SRH,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

# 15. Loading huge data into chunks

In [ ]:
pd.read_csv('matches.csv').shape

(1095, 20)

In [ ]:
# dividing into chunks
df = pd.read_csv('matches.csv',chunksize=200)

In [ ]:
for chunks in df:
  print(chunks.shape)

(200, 20)
(200, 20)
(200, 20)
(200, 20)
(200, 20)
(95, 20)